{
  parserClass="com.github.alaanor.candid.CandidParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Candid"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.alaanor.candid.psi"
  psiImplPackage="com.github.alaanor.candid.psi.impl"

  elementTypeHolderClass="com.github.alaanor.candid.CandidTypes"
  elementTypeClass="com.github.alaanor.candid.psi.CandidElementType"
  tokenTypeClass="com.github.alaanor.candid.psi.CandidTokenType"
}

candidFile ::= prog
prog ::= (def';')*

def ::= TYPE id OP_EQ data_type

private field_type ::= nat_type ':' data_type | name ':' data_type
private data_type ::= id | prim_type | comp_type
private comp_type ::= cons_type | ref_type
private prim_type ::= num_type | BOOL | TEXT | NULL | RESERVED | EMPTY | PRINCIPAL
private num_type ::= NAT | NAT8 | NAT16 | NAT32 | NAT64
        | INT | INT8 | INT16 | INT32 | INT64
        | FLOAT32 | FLOAT64
private cons_type ::= OPT data_type
        | VEC data_type
        | RECORD '{' (field_type';')* '}'
        | VARIANT '{' (field_type';')* '}'
private ref_type ::= FUNC func_type | SERVICE actor_type
private nat_type ::= num | '0x'hex_num

num ::= digit('_'? digit)*
hex_num ::= hex('_'? hex)*
name ::= id | text_type
text_type ::= '"'char*'"'
char ::= utf8 | '\' hex hex | '\' escape | // '\ u{'hexnum'}' @TODO
escape ::= 'n' | 'r' | 't' | '\' | '"' | "'"
utf8 ::= ascii // TODO utf8enc
